### ISSUE TITLE
What does it mean？？

### ISSUE THREAD

**Issue by abilly007** [Tessares/libconvert#13]
Usage:
CONVERT_ADDR = 192.0.2.1 CONVERT_PORT = 1234 LD_PRELOAD =. / Libconvert_client.so curl https://www.tessares.net
What's the address of CONVERT_ADDR here? What is this CONVERT_PORT port, and who is listening?
Or is it just testing whether the SYN packet from the local host to the (www.tessares.net) | 137.74.198.163 host carries CONVERT_ADDR and CONVERT_PORT information?

**Comment by GregoryVds** [comment]
Hi,

CONVERT_ADDR/PORT is the address and port number of the Converter. 

At the moment, this library only includes a client-side implementation, but not a server-side implementation (the Converter itself). 192.0.2.1:1234 is just a dummy address for the example.

However there is a [mock Converter](https://github.com/Tessares/libconvert/blob/master/tests/converter_mock.py) in the tests directory that you could use to test the client.

www.tessares.net does not implement the Converter, so you will not be able to test against it. 
Unfortunately I am unaware of any Converter available for testing purpose on the public Internet.

**Comment by abilly007** [comment]
HI,GregoryVds.
    Thank you very much for your reply. But I still don't understand the principle of this test command. I have the following questions. 
1. First, my test setup as follows:
![convert1](https://user-images.githubusercontent.com/37547039/70600569-f900ba00-1c2a-11ea-99dd-3e05a0f0fd1d.png)

2. I execute the following command on host 1:
[root@localhost build]# CONVERT_ADDR=172.171.50.99 CONVERT_PORT=1234 LD_PRELOAD=./libconvert_client.so wget -4 http://www.tessares.net/ -t1 -O -
and the result is ok as follows:
[root@localhost build]# CONVERT_ADDR=172.171.50.99 CONVERT_PORT=1234 LD_PRELOAD=./libconvert_client.so wget -4 http://www.tessares.net/ -t1 -O -
--2019-12-11 23:10:45--  http://www.tessares.net/
正在解析主机 www.tessares.net (www.tessares.net)... 137.74.198.163
正在连接 www.tessares.net (www.tessares.net)|137.74.198.163|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 301 Moved Permanently
位置：https://www.tessares.net/ [跟随至新的 URL]
--2019-12-11 23:10:50--  https://www.tessares.net/
正在连接 www.tessares.net (www.tessares.net)|137.74.198.163|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 403 Forbidden
2019-12-11 23:10:51 错误 403：Forbidden。

[root@localhost build]# 	

3. But I only catch the syn message with payload on host2. The load content is the real server IP, but the connection was rst, and the data transmission is not transferred through the converter?? But directly from the host1 to the server, without taking the multi-path of MPTCP, how can we realize convert as the connecting transit station? 
![convert](https://user-images.githubusercontent.com/37547039/70600796-95c35780-1c2b-11ea-8d97-b36644593da9.png)

4. The test cases are not all passed, and the results are as follows:
![convert2](https://user-images.githubusercontent.com/37547039/70600890-d4f1a880-1c2b-11ea-92dc-e86082abdd60.png)

Thanks!

**Comment by GregoryVds** [comment]
Hi,

What program are you running on host2 to act as the server-side Converter? Do you have a Converter app listening on port 1234? The trace looks good, however it looks like the port is not open on host2. 

172.171.50.99 is the addr of host2, right? 
 
Thanks for mentioning the test-suite is broken. It didn't run for the past 10 months, so I am not surprised :-) I will have a look and try to fix that ASAP

**Comment by abilly007** [comment]
Thanks your reply.
yes,the ip 172.171.50.99 is the host2 as the Converter  of server-side, but there are no program listening on port 1234 , you had said a server-side implementation (the Converter itself) is the one program listening on port 1234 and convert all the sessions between the client and server?

**Comment by GregoryVds** [comment]
That's correct, the server-side implementation should convert the session between the client and the server and it should be running on host2, listening at 172.171.50.99:1234. 

If I understand you correctly, you only have the client in your setup, so it cannot work.

You need a server-side implementation that will relay the data between the client<->converter MPTCP connection and the converter<->server TCP connection. We don't have such an implemention in this repo at the moment.

You could implement a toy Converter server using the library and TPROXY for instance.

**Comment by GregoryVds** [comment]
Hey,

What kernel are you using? I just noticed that the current version does not run on kernel 5+.
I just pushed a fix for that (https://github.com/Tessares/libconvert/pull/14/commits)
I also updated the README with some clarifications based on your questions and remarks.

Running the tests locally is quite hard as you need all the correct deps (scapy, cppcheck, uncrustify, etc). Check the .travis.yaml file for a complete list of deps. In the future we should provide a Dockerfile with all the deps to ease the testing.

**Comment by GregoryVds** [comment]
@abilly007 I added a Dockerfile to easily run the tests & build.
You should be able to run the tests as follows:

```
$ docker build -t tessares.net/libconvert .
$ docker run --cap-add=NET_ADMIN --sysctl net.ipv4.tcp_fastopen=5 -v $PWD:/lc -t tessares.net/libconvert /bin/bash -c "mkdir -p /lc/build && cd /lc/build && cmake .. && make && make test"
```  

Please let me know if this works ok for you.

I suppose you were simply missing the dependencies:
- scappy for the actual tests
- uncrustify/cppcheck/scan-build for the linting tests

**Comment by GregoryVds** [comment]
Closing issue. Please reach out if you still need help.
